site_name: Vault Wiki
theme:
  name: material
  features:
  - navigation.instant
  - navigation.sections
  - navigation.path
  - navigation.top
  - navigation.indexes
  - toc.follow
markdown_extensions:
- toc:
    permalink: true
- tables
- fenced_code
extra_css:
- stylesheets/extra.css
nav:
- "\U0001F3E0 Home": index.md
- "\U0001F9EA Sample Page": sample-page.md
